---
- name: Converge
  hosts: all
  roles:
    - role: ansible-tags-article-code



  tasks:
    - include_role:
        name: ansible-tags-article-code



    - name: configure tools
      import_role:
        name: limepepper.min-utils
        tasks_from: main.yml
